[pytest]
python_files = ["*.py"]
python_functions = ["main"]
filterwarnings = ["error"]
markers = ["slow: takes more than 30s to run"]
addopts = ["--cov=sirf", "--cov-append"]
# see also: conftest.py
