function prep_data = preprocess_acquisitions(input_data)
% Apply NoiseAdjust, AsymmetricEchoAdjust and RemoveROOversampling gadgets
prep_data = input_data.process([ ...
    {'NoiseAdjustGadget'} ...
    {'AsymmetricEchoAdjustROGadget'} ...
    {'RemoveROOversamplingGadget'} ...
    ]);
end