#pragma once
//
//
// This file is for doxygen only. It does not contain any code.
/*
CCP PETMR Synergistic Image Reconstruction Framework (SIRF)
Copyright 2015 - 2017 Rutherford Appleton Laboratory STFC

This is software developed for the Collaborative Computational
Project in Positron Emission Tomography and Magnetic Resonance imaging
(http://www.ccppetmr.ac.uk/).

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/

/*!
\mainpage

This html document contains detailed information about software package SIRF
developed by Synergistic Image Reconstruction Framework for the Collaborative 
Computational Project in Positron Emission Tomography and Magnetic Resonance 
imaging (CCP PET-MR).

Additional documentation is given in the SIRF User's Guide, which, alongside
with overview documents etc., can be found on the CCP PET-MR website 
http://www.ccppetmr.ac.uk. You are advised to read those first before looking 
into the documentation presented here.

The current pages are automatically generated by doxygen from text comments 
in the files.

*/