if (NOT _ZENODO_RETRY_INCLUDED)
  set(_ZENODO_RETRY_INCLUDED TRUE)

  function(get_zenodo_file path url md5)
    # already present and correct? skip the network entirely.
    if (EXISTS "${path}")
      file(MD5 "${path}" _have_md5)
      string(TOLOWER "${_have_md5}" _have_md5)
      string(TOLOWER "${md5}" _want_md5)
      if (_have_md5 STREQUAL _want_md5)
        message(STATUS "Using existing ${path}")
        return()
      endif()
    endif()
    message(STATUS "Downloading...
		Path:     ${path}
		URL:      ${url}
		MD5:      ${md5}")
    set(_attempt 0)
    set(_max_attempts 5)
    set(_status "UNKNOWN")
    while (_attempt LESS _max_attempts)
      # Note: cmake<3.31: failed download + EXPECTED_MD5 errors, so check md5 manually
      file(DOWNLOAD "${url}" "${path}" SHOW_PROGRESS STATUS _result)
      list(GET _result 0 _status)
      list(GET _result 1 _status_msg)
      if (_status EQUAL 0)
        file(MD5 "${path}" _actual_md5)
        string(TOLOWER "${_actual_md5}" _actual_md5)
        string(TOLOWER "${md5}" _want_md5)
        if (_actual_md5 STREQUAL _want_md5)
          return()
        endif()
        set(_status "MD5-MISMATCH")
        set(_status_msg "expected ${_want_md5}, got ${_actual_md5}")
      endif()
      math(EXPR _attempt "${_attempt} + 1")
      if (_attempt LESS _max_attempts)
        message(STATUS "Download failed (attempt ${_attempt}/${_max_attempts}, status ${_status} ${_status_msg}); retrying in 5s...")
        execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 5)
      endif()
    endwhile()
    message(FATAL_ERROR "Failed to download ${url} after ${_max_attempts} attempts (status ${_status} ${_status_msg})")
  endfunction()

endif()
