name: cffconvert
on: {push: {paths: [CITATION.cff]}}
jobs:
  validate:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v7
    - name: Check whether the citation metadata from CITATION.cff is valid
      uses: citation-file-format/cffconvert-github-action@2.0.0
      with: {args: --validate}
