!INTERFILE  :=
!imaging modality := PT
name of data file := my_forward_projection.s
originating system := PRT-1
!version of keys := STIR3.0
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {arc correction}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 9
matrix axis label [3] := view
!matrix size [3] := 96
matrix axis label [2] := axial coordinate
!matrix size [2] := { 12,13,14,15,16,15,14,13,12}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 128
minimum ring difference per segment := { -4,-3,-2,-1,0,1,2,3,4}
maximum ring difference per segment := { -4,-3,-2,-1,0,1,2,3,4}
Scanner parameters:= 
Scanner type := PRT-1
Number of rings                          := 16
Number of detectors per ring             := 384
Inner ring diameter (cm)                 := 74.6
Average depth of interaction (cm)        := 0.7
Distance between rings (cm)              := 0.675
Default bin size (cm)                    := 0.31088
View offset (degrees)                    := 0
Maximum number of non-arc-corrected bins := 128
Default number of arc-corrected bins     := 128
Number of blocks per bucket in transaxial direction         := 4
Number of blocks per bucket in axial direction              := 1
Number of crystals per block in axial direction             := 8
Number of crystals per block in transaxial direction        := 8
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := 8
Number of crystals per singles unit in transaxial direction := 32
end scanner parameters:=
effective central bin size (cm) := 0.31088
number of time frames := 1
!END OF INTERFILE :=
